name: Reusable Build and Push Workflow

# List of required fields for github workflow
on:
  workflow_call:
    inputs:
      container_name:
        required: true
        type: string
      container_path:
        required: true
        type: string
      container_file:
        required: true
        type: string
      commit_sha:
        required: true
        type: string
      container_tag:
        required: false
        type: string
        default: latest
      build_target:
        required: false
        type: string
        default: base
      download_artifact:
        required: false
        type: boolean
        default: false
      artifact_name:
        required: false
        type: string
      default_branch:
        required: false
        type: string
        default: refs/heads/main
    secrets:
      PODMAN_TOKEN:
        required: true

env:
  REGISTRY_URL: ghcr.io/${{ github.repository_owner }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Setup Podman to use container registry
      - name: Login Podman
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PODMAN_TOKEN }}
          registry: ${{ env.REGISTRY_URL }}

      # Checkout the repository to get the files
      - name: Checkout latest code
        uses: actions/checkout@v3

      # Download artifacts
      - name: Download artifact
        if: inputs.download_artifact == true
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ./${{ inputs.container_path }}

      # Build and push the container
      - name: Build and push container
        run: |
          echo "Building container: ${{ inputs.container_name }}:${{ inputs.commit_sha }}"
          
          cd ${{ inputs.container_path }}
          podman build \
            --target ${{ inputs.build_target }} \
            -f ${{ inputs.container_file }} \
            -t ${{ env.REGISTRY_URL }}/${{ inputs.container_name }}:${{ inputs.commit_sha }} \
            --build-arg=DEV_CONTAINER_SHA=${{ inputs.commit_sha }} .
          podman push ${{ env.REGISTRY_URL }}/${{ inputs.container_name }}:${{ inputs.commit_sha }}

      # Push container as stable
      - name: Push container to stable
        if: github.ref == inputs.default_branch
        run: |
          # retag as latest
          podman tag ${{ env.REGISTRY_URL }}/${{ inputs.container_name }}:${{ inputs.commit_sha }} \
                     ${{ env.REGISTRY_URL }}/${{ inputs.container_name }}:latest

          # retag as desired container tag:
          podman tag ${{ env.REGISTRY_URL }}/${{ inputs.container_name }}:${{ inputs.commit_sha }} \
                     ${{ env.REGISTRY_URL }}/${{ inputs.container_name }}:${{ inputs.container_tag }}

          # push
          podman push ${{ env.REGISTRY_URL }}/${{ inputs.container_name }}:latest
          podman push ${{ env.REGISTRY_URL }}/${{ inputs.container_name }}:${{ inputs.container_tag }}

