name: Reusable Build and Push Workflow

# List of required fields for github workflow
on:
  workflow_call:
    inputs:
      # ubuntu-24.04 or ubuntu-24.04-arm
      runner:
        required: false
        type: string
        default: ubuntu-24.04
      container_name:
        required: true
        type: string
      container_path:
        required: true
        type: string
      container_file:
        required: true
        type: string
      container_tag:
        required: true
        type: string
      build_target:
        required: false
        type: string
        default: base
    secrets:
      PODMAN_TOKEN:
        required: true

env:
  REGISTRY_URL: ghcr.io/${{ github.repository_owner }}
  DEFAULT_BRANCH: main

jobs:
  build_and_push:
    runs-on: ${ARCH} 
    steps:
      # Setup Podman to use container registry
      - name: Login Podman
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PODMAN_TOKEN }}
          registry: ${{ env.REGISTRY_URL }}

      # Checkout the repository to get the files
      - name: Checkout latest code
        uses: actions/checkout@v4

      # Build and push the container
      - name: Build and push container
        run: |
          # print architecture
          export ARCH=$(dpkg --print-architecture)

          # build container
          echo "Building container: ${{ inputs.container_name }}:${{ inputs.container_tag }}"
          
          cd ${{ inputs.container_path }}
          podman build \
            --target ${{ inputs.build_target }} \
            -f ${{ inputs.container_file }} \
            -t ${{ env.REGISTRY_URL }}/${{ inputs.container_name }}:${{ inputs.container_tag }} .
          podman push ${{ env.REGISTRY_URL }}/${{ inputs.container_name }}-${ARCH}:${{ inputs.container_tag }}

          # Publish latest stable build as latest tag
          if [[ "${GITHUB_REF}" == "refs/heads/${{ env.DEFAULT_BRANCH }}" ]]; then
            podman tag ${{ env.REGISTRY_URL }}/${{ inputs.container_name }}:${{ inputs.container_tag }} \
                       ${{ env.REGISTRY_URL }}/${{ inputs.container_name }}:latest
            podman push ${{ env.REGISTRY_URL }}/${{ inputs.container_name }}:latest
          fi

