name: Reusable Build and Push Workflow

# List of required fields for github workflow
on:
  workflow_call:
    inputs:
      # ubuntu-24.04 or ubuntu-24.04-arm
      runner:
        required: false
        type: string
        default: ubuntu-24.04
      container_name:
        required: true
        type: string
      container_path:
        required: true
        type: string
      container_file:
        required: false
        type: string
        default: Containerfile
      container_tag:
        required: true
        type: string
      build_target:
        required: false
        type: string
        default: base
    secrets:
      CONTAINER_TOKEN:
        required: true

env:
  REGISTRY_URL: ghcr.io/${{ github.repository_owner }}
  DEFAULT_BRANCH: main

jobs:
  build_and_push:
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: read
      packages: write
    steps:
      # Login Docker
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_TOKEN }}
          registry: ${{ env.REGISTRY_URL }}

      # Checkout the repository to get the files
      - name: Checkout latest code
        uses: actions/checkout@v4

      # Use pre-defined docker build and push
      - name: Build and Push Container
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.container_path }}
          file: ${{ inputs.container_file }}
          target: ${{ inputs.build_target }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${REGISTRY_URL}/${{ inputs.container_name }}:${{ inputs.container_tag }}
            ${GITHUB_REF == 'refs/heads/${DEFAULT_BRANCH}' && "${REGISTRY_URL}/${inputs.container_name}:latest" || ""}
