name: Reusable Build and Push Workflow

# List of required fields for github workflow
on:
  workflow_call:
    inputs:
      container_name:
        required: true
        type: string
      container_file:
        required: false
        type: string
        default: Containerfile
      container_tag:
        required: false
        type: string
        default: latest
      build_target:
        required: false
        type: string
        default: base
      build_args:
        description: |
          Multiline list of build‑args, e.g.
          FOO=bar
          BAZ=baz
        required: false
        type: string
        default: ""
    secrets:
      CONTAINER_TOKEN:
        required: true

env:
  REGISTRY_URL: ghcr.io/${{ github.repository_owner }}
  DEFAULT_BRANCH: main

jobs:
  # build amd64
  build_amd64:
    uses: amidg/workflows/.github/workflows/build_docker_and_push.yml@main
    with:
      container_name: ${{ inputs.container_name }}
      container_file: ${{ inputs.container_file }}
      container_tag:  ${{ github.sha }}-amd64
      runner: ubuntu-24.04
      build_target: ${{ inputs.build_target }}
      build_args: ${{ inputs.build_args }}
    secrets:
      CONTAINER_TOKEN: ${{ secrets.CONTAINER_TOKEN }}

  # build arm64
  build_arm64:
    uses: amidg/workflows/.github/workflows/build_docker_and_push.yml@main
    with:
      container_name: ${{ inputs.container_name }}
      container_file: ${{ inputs.container_file }}
      container_tag:  ${{ github.sha }}-arm64
      runner: ubuntu-24.04-arm
      build_target: ${{ inputs.build_target }}
      build_args: ${{ inputs.build_args }}
    secrets:
      CONTAINER_TOKEN: ${{ secrets.CONTAINER_TOKEN }}

  # build manifest to allow to push multiarch image
  create_manifest:
    needs:
      - build_amd64
      - build_arm64
    runs-on: ubuntu-24.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_TOKEN }}
          registry: ${{ env.REGISTRY_URL }}

      # Set correct tags for the container
      # GitHub actions do not support nested expressions
      - name: Set Tags
        id: set-tags
        run: |
          TAGS="${{ env.REGISTRY_URL }}/${{ inputs.container_name }}:${{ inputs.container_tag }}"
          if [[ "${GITHUB_REF}" == "refs/heads/${{ env.DEFAULT_BRANCH }}" ]]; then
            TAGS="${{ env.REGISTRY_URL }}/${{ inputs.container_name }}:latest"
          fi
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Create and push manifest list
        run: |
          # create manifest
          docker manifest create \
            ${{ steps.set-tags.outputs.tags }} \
            ${REGISTRY_URL}/${{ inputs.container_name }}:${{ inputs.container_tag }}-amd64 \
            ${REGISTRY_URL}/${{ inputs.container_name }}:${{ inputs.container_tag }}-arm64

          # push manifest
          docker manifest push ${{ steps.set-tags.outputs.tags }}
