name: Example main.yml to be placed in your .github/workflows

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  # build test container with docker
  build_test_container_with_docker:
    uses: amidg/workflows/.github/workflows/build-docker-and-push.yml@main
    strategy:
      matrix:
        container:
          - name: workflow-docker-test
            path: .
            file: Containerfile
    with:
      container_name: ${{ matrix.container.name }}
      container_path: ${{ matrix.container.path }}
      container_file: ${{ matrix.container.file }}
      container_tag:  ${{ github.sha }}
    secrets:
      CONTAINER_TOKEN: ${{ secrets.CONTAINER_TOKEN }}
