name: Example main.yml to be placed in your .github/workflows

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  # build test container with docker (amd64)
  build_test_container_with_docker_amd64:
    uses: amidg/workflows/.github/workflows/build-docker-and-push.yml@main
    strategy:
      matrix:
        container:
          - name: workflow-docker-test
            path: .
            file: Containerfile
    with:
      container_name: ${{ matrix.container.name }}
      container_path: ${{ matrix.container.path }}
      container_file: ${{ matrix.container.file }}
      container_tag:  ${{ github.sha }}
      runner: ubuntu-24.04
    secrets:
      CONTAINER_TOKEN: ${{ secrets.CONTAINER_TOKEN }}

  # build test container with docker (arm64)
  build_test_container_with_docker_arm64:
    uses: amidg/workflows/.github/workflows/build-docker-and-push.yml@main
    strategy:
      matrix:
        container:
          - name: workflow-docker-test
            path: .
            file: Containerfile
    with:
      container_name: ${{ matrix.container.name }}
      container_path: ${{ matrix.container.path }}
      container_file: ${{ matrix.container.file }}
      container_tag:  ${{ github.sha }}
      runner: ubuntu-24.04-arm
    secrets:
      CONTAINER_TOKEN: ${{ secrets.CONTAINER_TOKEN }}
