name: Example main.yml to be placed in your .github/workflows

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  # build test manifest
  test_docker_multiarch:
    uses: amidg/workflows/.github/workflows/build_docker_multiarch.yml@main
    strategy:
      matrix:
        container:
          - name: workflow-docker-test
            path: .
            file: Containerfile
    with:
      container_name: ${{ matrix.container.name }}
      container_file: ${{ matrix.container.path }}/${{ matrix.container.file }}
      container_tag:  ${{ github.sha }}
      build_args: |
        UBUNTU_VERSION=24.04
    secrets:
      CONTAINER_TOKEN: ${{ secrets.CONTAINER_TOKEN }}
